### ISSUE TITLE
Plugin doesn't work - stuck on loading

### ISSUE THREAD

**Issue by philipamour** [glmrvn/figma-dark-mode-plugin#23]
I've created color variables with the following names:
`Color/Background`
`Dark/Background`
and changed Appearance settings to use `Color` for light styles and `Dark` for dark styles.

When running the plugin (e.g. Appearance -> Dark Mode), the plugin gets stuck on `Running Appearance`. The console shows the following:
```Failed to load resource: the server responded with a status of 404 ()
/api/design_systems/library/styles/----------:1 Failed to load resource: the server responded with a status of 404 ()
static.figma.com/fullscreen/----------/jsvm-cpp.js.br:8 unhandled promise rejection: TypeError: cannot read property 'name' of undefined
printChar @ static.figma.com/fullscreen/----------/jsvm-cpp.js.br:8
static.figma.com/fullscreen/----------/jsvm-cpp.js.br:8     at getPaints (PLUGIN_9_SOURCE:146)
printChar @ static.figma.com/fullscreen/----------/jsvm-cpp.js.br:8
```

https://www.figma.com/file/uC1HjQawIe0IIUDFlKlMK3/Appearance-Plugin-Error?node-id=0%3A1

**Comment by glmrvn** [comment]
Hello. I pushed update 3 days ago. Please check it out. Plugin updated automatically in Figma. 
I checked your sample file and plugin works.

**Comment by philipamour** [comment]
I've just checked again - reinstalled plugin, etc. and for some reason this only happens on the desktop app and not the browser version of Figma. Also in organization files that use components and link to colors in a design system file, I keep getting the "Selection does not have style pairs" error - any ideas on what that may be caused by? (I can't share affected files as they are my employer's IP 🙁)

**Comment by philipamour** [comment]
Quick update - managed to get the sample file to work after re-downloading Figma and deleting caches. The issue with design system/libraries still persists. 🙁

**Comment by philipamour** [comment]
Just tested a hypothesis and the plugin is working fine as long as it's getting used in a file where the shared colors live. It doesn't seem to work if I have a Design System file with all the colors and then work in a separate file that links to those colors.

**Comment by glmrvn** [comment]
I fix issue with local files. Plugin updated automatically. Please check your cases.

**Comment by philipamour** [comment]
Hi, I'm still seeing "Selection does not have style pairs" error when trying to change appearance in a figma file that's using color styles from a team library.

**Comment by glmrvn** [comment]
Please select "Save styles" in the plugin menu in your team library file. And check settings in the plugin menu.
Then go to the connected file and try use dark/light mode.

**Comment by philipamour** [comment]
That seemed to allow switching between dark and light mode; however, only some components/layers are affected - even tho all of the components and layers are using styles with matching pairs. 🙁

**Comment by philipamour** [comment]
Actually - this seems to be a bug with figma when for some reason updating color value in the library would have no effect on some layers in the library or in linked files. Going to go through many pages now to re-select the same color styles. It looks like the plugin works as intended, the only problem is Figma bugs now. Thank you so much for your help! ❤️
